### ISSUE TITLE
Feature: Quadratic Calculator in JS

### ISSUE THREAD

**Issue by RahulSahOfficial** [keshavsingh4522/hacktoberfest2021#2151]
### Is your feature request related to a problem? Please describe.

There should be a quadratic calculator in JS folder in which user can find roots by entering the equation

### Describe the solution you'd like

Using HTML CSS JS I can make the quadratic calulator 

Assign it to me

**Comment by Abhishek-PratapSingh** [comment]
@keshavsingh4522 I can do it easily #2151

**Comment by RahulSahOfficial** [comment]
@Abhishek-PratapSingh 
But I want to work on it
Check the last line of Issue
You can create any similar calculator issue

**Comment by Abhishek-PratapSingh** [comment]
@RahulSahOfficial ok but you are not assigned till now
