### ISSUE TITLE
Feature: Password Generator in JS

### ISSUE THREAD

**Issue by RahulSahOfficial** [keshavsingh4522/hacktoberfest2021#2152]
### Is your feature request related to a problem? Please describe.

There should be a password generator in JS by which user can generate randomized passwords

### Describe the solution you'd like

By HTML CSS JS I can make a web app where user can generate random password and copy to clipboard

Assign it to me

**Comment by MAGICTNT** [comment]
I would also like to work on it

**Comment by deepdarshan21** [comment]
want to work on it

**Comment by vivekarora-02** [comment]
Hey there,
Can you please assign me this issue?

ThankYou!
